- name: Install packages
  package:
    name: ['bridge-utils']
    state: installed
    update_cache: yes

- name: Enable IP Masquerading on outbound eth0 
  become: true
  become_user: root
  shell: sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

- name: Save iptables rules 
  become: true
  become_user: root
  shell: sudo sh -c "iptables-save > /etc/iptables.ipv4.nat"

- name: Create a new bridge 
  become: true
  become_user: root
  shell: brctl addbr br0

- name: Connect etho0 to bridge 
  become: true
  become_user: root
  shell: brctl addif br0 eth0

- name: Copy network interfaces file and backup old one
  ansible.builtin.copy:
    src: /etc/pilink/configs/network/interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'
    backup: yes