## Wireless Network Interface: wlan0
- hosts: localhost
  connection: local 
  become: yes
  become_method: sudo
  any_errors_fatal: true

  tasks: 
    - name: Install Wireless Access packages
      package:
        name: ['hostapd']
        state: present
        update_cache: yes

    - name: Disable Wireless Access Service
      systemd:
        name: 'hostapd'
        enabled: false

    - name: Copy hostapd config file and backup old one
      ansible.builtin.copy:
        src: /etc/pilink/configs/hostapd/hostapd.conf
        dest: /etc/hostapd/hostapd.conf
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: Copy hostapd default file and backup old one
      ansible.builtin.copy:
        src: /etc/pilink/configs/hostapd/hostapd
        dest: /etc/default/hostapd
        owner: root
        group: root
        mode: '0644'
        backup: yes
