version: '3.7'
services:
# TODO: Expose Devices /dev/tty*
#       Enable optimizations
  homeassistant:
      container_name: homeassistant
      restart: unless-stopped
      image: homeassistant/raspberrypi4-homeassistant:stable
      privileged: true
      network_mode: host
      environment:
        - PUID=1001
        - PGID=1001
      volumes:
        - /etc/pilink/configs/homeassistant:/config
        - /etc/localtime:/etc/localtime:ro