global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  
  - job_name: "dnsmasq_exporter"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['0.0.0.0:9153']  

  - job_name: "mqtt2prometheus"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['ADD_PI_IP_HERE:9641']
