global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  
  - job_name: "ha"
    scrape_interval: 60s
    metrics_path: /api/prometheus
    scheme: http
    bearer_token: 'ADD_TOKEN_HERE'
    static_configs:
      - targets: ['ADD_PI_IP_HERE:8123']
      
  # - job_name: dnsmasq
  #   static_configs:
  #     - targets: ['localhost:9153']
