- hosts: localhost
  connection: local 
  become: yes
  become_method: sudo
  any_errors_fatal: true

  tasks: 
    - name: Install Prerequisite Docker packages
      package:
        name: ['{{ item }}']
        state: present
        update_cache: yes
        with_items:
          - 'apt-transport-https'
          - 'ca-certificates'
          - 'curl'
          - 'gnupg-agent'
          - 'software-properties-common'
          - 'libffi-dev'
          - 'libssl-dev'
          - 'python3'
          - 'python3-pip'
    
    - name: Make sure python-configparser is removed
      package:
        name: ['{{ python-configparser }}']
        state: absent
        update_cache: yes
    
    - name: Add Docker-CE GPG Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu groovy stable
        state: present

    - name: Install Docker-CE packages
      package:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        state: present
        update_cache: yes

    - name: Install docker-compose
      shell: pip3 -v install docker-compose

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Enable services
      systemd:
        name: 'docker.service'
        enabled: yes