- hosts: localhost
  connection: local 
  become: yes
  become_method: sudo
  any_errors_fatal: true

  tasks: 
    - name: Install Prerequisite Docker packages
      package:
        name: ['{{ item }}']
        state: present
      with_items:
          - 'apt-transport-https'
          - 'ca-certificates'
          - 'curl'
          - 'gnupg-agent'
          - 'software-properties-common'
          - 'libffi-dev'
          - 'libssl-dev'
          - 'python3'
          - 'python3-pip'
    
    - name: Get Host IP Addr
      shell: ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1
      register: host_ip

    - name: Copy mqtt2prometheus config
      copy:
        src:  ../../services/mqtt2prometheus/example-config.yaml
        dest: ../../services/mqtt2prometheus/config.yaml
        owner: root
        group: sys
        mode: '0644'
        backup: yes
    
    - name: Copy prometheus config
      copy:
        src:  ../../services/prometheus/example-prometheus.yml
        dest: ../../services/prometheus/prometheus.yml
        owner: root
        group: sys
        mode: '0644'
        backup: yes