- hosts: localhost
  connection: local 
  become: yes
  become_method: sudo

  tasks: 
    - name: Create HA User
      user:
        name: "ha"
        comment: "Home Assistant"
        createhome: yes 
        system: yes
        shell: /bin/bash
    
    - name: Add ha to docker group
      user:
        name: ha
        groups: sudo 
        append: yes
