- hosts: localhost
  connection: local 
  become: yes
  become_method: sudo
  any_errors_fatal: true

  tasks: 
    - name: Install DNS and DHCP packages
      package:
        name: ['dnsmasq', 'isc-dhcp-server']
        state: present

    - name: Disable Existing DNS and make sure dnsmasq is off
      service:
        name: "{{ item }}"
        enabled: false
      with_items:
          - 'dnsmasq'
          - 'isc-dhcp-server'

    - name: Copy dhcpd config file and backup old one
      copy:
        src:  ../../configs/system/dhcpd.conf
        dest: /etc/dhcp/dhcpd.conf
        owner: root
        group: sys
        mode: '0644'
        backup: yes

    - name: Copy dnsmasq config file and backup old one
      copy:
        src:  ../../configs/system/dnsmasq.conf
        dest: /etc/dnsmasq.conf
        owner: root
        group: sys
        mode: '0644'
        backup: yes

    - name: Copy isc-dhcp config file and backup old one
      copy:
        src:  ../../configs/system/isc-dhcp-server
        dest: /etc/default/isc-dhcp-server
        owner: root
        group: sys
        mode: '0644'
        backup: yes
    
    - name: Copy resolve config file and backup old one
      copy:
        src:  ../../configs/system/resolved.conf
        dest:  /etc/resolv.conf
        owner: root
        group: sys
        mode: '0644'
        backup: yes

    - name: Make sure /var/db folder exists
      file: 
          path: /var/db
          owner: root 
          group: root 
          mode: 0755 
          state: directory

    - name: Make sure DHCP Lease file exists
      copy:
          content: ""
          dest: /var/db/dhcp.leases
          owner: root
          group: root
          mode: '0644'
          force: no  
        
    - name: Remove old DNS package
      package:
        name: ['systemd-resolved']
        state: absent

    - name: Disable Existing DNS and make sure dnsmasq is off
      service:
        name: "{{ item }}"
        enabled: false
      with_items:
          - 'systemd-resolved'

    - name: Force unmask systemd-resolved
      shell: systemctl unmask systemd-resolved 

    - name: Force stop systemd-resolved
      shell: systemctl stop systemd-resolved 

    - name: Force disable systemd-resolved
      shell: systemctl disable systemd-resolved 
    
    - name: Force mask systemd-resolved
      shell: systemctl mask systemd-resolved 

    - name: Enable dnsmasq
      shell: systemctl restart dnsmasq 
