# Playbook for configuring UFW firewall
# Documentation: https://docs.ansible.com/ansible/latest/collections/community/general/ufw_module.html

#TODO: In UFW after.rules source is 192.168.1.0/24. Will need to be changed

- hosts: localhost
  connection: local 
  become: yes
  become_method: sudo
  any_errors_fatal: true

  tasks: 
    - name: Set Firewall Logging
      community.general.ufw:
        logging: 'on'

    - name: Allow DHCP traffic on wlan0 (Wireless)
      community.general.ufw:
        rule: allow
        interface: wlan0
        direction: in
        proto: udp
        src: any
        from_port: '68'
        dest: any
        to_port: '67'

    - name: Allow DNS traffic on wlan0 (Wireless)
      community.general.ufw:
        rule: allow
        interface: wlan0
        direction: in
        proto: udp
        src: 10.1.1.10/24
        dest: any
        to_port: '53'

    - name: Copy ufw config file and backup old one
      ansible.builtin.copy:
        src:  ../../configs/ufw/ufw
        dest: /etc/ufw
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: Copy ufw rules and backup old one
      ansible.builtin.copy:
        src:  ../../configs/ufw/{{item}}.rules
        dest: /etc/ufw/{{item}}.rules
        owner: root
        group: root
        mode: '0644'
        backup: yes
      with_items:
          - 'before'
          - 'after'

    - name: Reload UFW and Allow everything
      community.general.ufw:
        state: reloaded
        policy: allow
