- hosts: localhost
  connection: local 
  become: yes
  become_method: sudo
  any_errors_fatal: true

  tasks: 
    - name: Install Traffic Bridge packages
      package:
        name: ['bridge-utils']
        state: present
        update_cache: yes

    - name: Create a new bridge 
      become: true
      become_user: root
      shell: brctl addbr br0

    - name: Connect etho0 to bridge 
      become: true
      become_user: root
      shell: brctl addif br0 eth0

    - name: Copy network interfaces file and backup old one
      copy:
        src:  ../../configs/network/interfaces
        dest: /etc/network/interfaces
        owner: root
        group: root
        mode: '0644'
        backup: yes