## Wireless Network Interface: wlan0
- hosts: localhost
  connection: local 
  become: yes
  become_method: sudo

  tasks: 
    - name: Install Wireless Access packages
      package:
        name: ['hostapd', 'net-tools']
        state: present

    - name: Disable Wireless Access Service
      service:
        name: 'hostapd'
        enabled: false

    - name: Disable wlan0 interface
      command: ifconfig wlan0 down

    - name: Copy network interfaces file
      copy:
        src:  ../../configs/system/interfaces
        dest: /etc/network/interfaces
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: Copy hostapd config file
      copy:
        src:  ../../configs/system/hostapd.conf
        dest: /etc/hostapd/hostapd.conf
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: Copy hostapd default file 
      copy:
        src:  ../../configs/system/hostapd
        dest: /etc/default/hostapd
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: Copy sysctl default file 
      copy:
        src:  ../../configs/system/sysctl.conf
        dest: /etc/sysctl.conf
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: Enable wlan0 interface
      command: ifconfig wlan0 up

    - name: Configure wlan0 ip
      command:  ifconfig wlan0 10.1.1.1
   
    - name: Unmask hostapd
      become: true
      become_user: root
      shell : systemctl unmask hostapd

    - name: Force reenable hostapd
      become: true
      become_user: root
      shell: service hostapd restart

    - name: Enable hostapd on boot
      command: update-rc.d {{item}} enable
      with_items:
          - hostapd
