---
  - name: "Playing with Ansible and Git"
    hosts: localhost
    connection: local 
    tasks:

    - name: "List Directory"
      shell: "ls -lrt"
      register: "output"

    - debug: var=output.stdout_lines